Potentially done q3
Mburnand-tech/News_Server pull request #1
Opened 2023-01-16 15:33 UTC by Mburnand-tech

Not sure whether to do error handling

2023-01-16 15:49 UTC, Hard-Luck requested changes

2023-01-16 15:49 UTC, Hard-Luck commented on __tests__/app.test.js
> +        .then(( {body} ) => {
We want to test the length of the returned array.

2023-01-16 15:49 UTC, Hard-Luck commented on app/news.app.js
> +
add some sort of wildcard endpoint that returns a 404

2023-01-16 15:49 UTC, Hard-Luck commented on db/seeds/run-seed.js
> +console.log('Seeding happened')
Remove console.log

2023-01-16 15:49 UTC, Hard-Luck commented on models/news.models.js
> +        //console.log(Error)
remove commented code, also this test promise can never reject as "[]" is a truthy value, we only want to be testing for user errors.

2023-01-16 15:49 UTC, Hard-Luck commented on package.json
> +    "test": "PGDATABASE=nc_news_test jest",
we should be using .env files to set PGDATABASE

2023-01-18 09:47 UTC, itsaliabdallah commented on __tests__/app.test.js
> +
You should check that what you're returning as the length you're expecting

2023-01-18 09:54 UTC, itsaliabdallah commented on __tests__/app.test.js
> +            const article_idGiven = requestPath.slice(requestPath.indexOf('s/') + 2, requestPath.length) * 1
Im unsure why you have done this.
You are in control of the test suite, you can expect body.article_id.toBe '9'

2023-01-18 09:55 UTC, itsaliabdallah commented on __tests__/app.test.js
> +            expect(body.from).toBe('Express')
When testing an error you test the status which you have above. The thing to test next would be the body or message which you send back.

2023-01-18 09:57 UTC, itsaliabdallah commented on __tests__/app.test.js
> +            expect(body[0]).toHaveProperty('author')
the ticket just asks for the response to be an article object rather than the object inside an array.

2023-01-18 09:57 UTC, itsaliabdallah commented on __tests__/app.test.js
> +            expect(body.from).toBe('PSQL')
Same as above maybe also test the error message which you are sending back.

2023-01-18 10:00 UTC, itsaliabdallah commented on app/news.app.js
> +        response.status(400).send({status: err.status , from: errorHandler ,msg: '22P02: invalid_text_representation from Matt'})
Are you wanting to send the status twice in this way?

2023-01-18 10:02 UTC, itsaliabdallah commented on models/news.models.js
> +                JOIN comments
Try a LEFT JOIN here as any articles without comments will be skipped

2023-01-18 10:05 UTC, itsaliabdallah commented on models/news.models.js
> +const commentCounter = (queryData) => {
You could and probably should use SQL here to get the comment count.
Look at the SQL Aggregate Function Count

2023-01-18 10:06 UTC, itsaliabdallah commented on controllers/news.controllers.js
> +        response.status(200).send(article)
you're sending back an array here you should send this back as an object.

2023-01-18 14:13 UTC, merged